### ISSUE TITLE
"scale is not a function" with typography-theme-lincoln

### ISSUE THREAD

**Issue by faassen** [KyleAMathews/typography.js#98]
``typography-theme-lincoln`` uses the ``scale`` function at least in release ``0.15.0`` and ``0.14.0`` but doesn't appear to import it. I tried it in gatsby just now, and ``0.15.0`` gives the error during build time, and ``0.14.0`` initially seemed to work but then had the same error during runtime. ``0.13.0`` does work.

**Comment by KyleAMathews** [comment]
Hi can you paste in the error you're getting? I added `typography-theme-lincoln` 0.15.0 to the default starter and it seemed to work just fine in dev and when building (published it here http://stormy-feast.surge.sh/)

**Comment by bradennapier** [comment]
I have the same bug with the sutro theme:

Module build failed: TypeError: scale is not a function
    at Object.overrideStyles (/home/ubuntu/workspace/node_modules/typography-theme-sutro/dist/index.js:50:32)
    at module.exports (/home/ubuntu/workspace/node_modules/typography/dist/utils/createStyles.js:226:51)
    at Object.toJSON (/home/ubuntu/workspace/node_modules/typography/dist/index.js:74:41)
    at Object.toString (/home/ubuntu/workspace/node_modules/typography/dist/index.js:77:61)
    at /home/ubuntu/workspace/node_modules/postcss-typography/lib/index.js:20:40

**Comment by bradennapier** [comment]
This is due to a failure of the postcss-loader to keep up with your latest versions.

Removing node-modules from that module fixed it kind of
